//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BKDHEntities11 : DbContext
    {
        public BKDHEntities11()
            : base("name=BKDHEntities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChildProductRegistration> ChildProductRegistrations { get; set; }
        public virtual DbSet<DeletedChallanDetail> DeletedChallanDetails { get; set; }
        public virtual DbSet<DeletedChallanMain> DeletedChallanMains { get; set; }
        public virtual DbSet<DeletedCustomerMaster> DeletedCustomerMasters { get; set; }
        public virtual DbSet<DeletedPartyOrderDetail> DeletedPartyOrderDetails { get; set; }
        public virtual DbSet<DeletedPartyOrderMain> DeletedPartyOrderMains { get; set; }
        public virtual DbSet<DeletedProductDispatchDetail> DeletedProductDispatchDetails { get; set; }
        public virtual DbSet<DeletedPurchaseOrderDetail> DeletedPurchaseOrderDetails { get; set; }
        public virtual DbSet<DeletedPurchaseOrderMain> DeletedPurchaseOrderMains { get; set; }
        public virtual DbSet<DeletedSalesReturnDetail> DeletedSalesReturnDetails { get; set; }
        public virtual DbSet<DeletedSalesReturnMain> DeletedSalesReturnMains { get; set; }
        public virtual DbSet<Im_CurrentStock> Im_CurrentStock { get; set; }
        public virtual DbSet<Inv_M_ConfigMaster> Inv_M_ConfigMaster { get; set; }
        public virtual DbSet<Inv_M_SearchTypeMaster> Inv_M_SearchTypeMaster { get; set; }
        public virtual DbSet<Inv_M_UserMaster> Inv_M_UserMaster { get; set; }
        public virtual DbSet<Inv_M_UserPermissionMaster> Inv_M_UserPermissionMaster { get; set; }
        public virtual DbSet<M_BankMaster> M_BankMaster { get; set; }
        public virtual DbSet<M_BarCodeMaster> M_BarCodeMaster { get; set; }
        public virtual DbSet<M_BatchMaster> M_BatchMaster { get; set; }
        public virtual DbSet<M_BillTypeMaster> M_BillTypeMaster { get; set; }
        public virtual DbSet<M_BlockProductMaster> M_BlockProductMaster { get; set; }
        public virtual DbSet<M_BrandMaster> M_BrandMaster { get; set; }
        public virtual DbSet<M_CardIssue> M_CardIssue { get; set; }
        public virtual DbSet<M_CatMaster> M_CatMaster { get; set; }
        public virtual DbSet<M_CityStateMaster> M_CityStateMaster { get; set; }
        public virtual DbSet<M_CompanyMaster> M_CompanyMaster { get; set; }
        public virtual DbSet<M_CompBankersMaster> M_CompBankersMaster { get; set; }
        public virtual DbSet<M_CountryMaster> M_CountryMaster { get; set; }
        public virtual DbSet<M_CouponSalesDetail> M_CouponSalesDetail { get; set; }
        public virtual DbSet<M_CourierDetails> M_CourierDetails { get; set; }
        public virtual DbSet<M_CourierMaster> M_CourierMaster { get; set; }
        public virtual DbSet<M_CustomerMaster> M_CustomerMaster { get; set; }
        public virtual DbSet<M_DeleteTransaction> M_DeleteTransaction { get; set; }
        public virtual DbSet<M_DispatchMaster> M_DispatchMaster { get; set; }
        public virtual DbSet<M_DispatchTypeMaster> M_DispatchTypeMaster { get; set; }
        public virtual DbSet<M_DistrictMaster> M_DistrictMaster { get; set; }
        public virtual DbSet<M_DivisionMaster> M_DivisionMaster { get; set; }
        public virtual DbSet<M_ExtraDiscount> M_ExtraDiscount { get; set; }
        public virtual DbSet<M_FiscalMaster> M_FiscalMaster { get; set; }
        public virtual DbSet<M_FormGeneration> M_FormGeneration { get; set; }
        public virtual DbSet<M_GroupMaster> M_GroupMaster { get; set; }
        public virtual DbSet<M_InsuranceCompMaster> M_InsuranceCompMaster { get; set; }
        public virtual DbSet<M_InwardData> M_InwardData { get; set; }
        public virtual DbSet<M_InwardMain> M_InwardMain { get; set; }
        public virtual DbSet<M_JType> M_JType { get; set; }
        public virtual DbSet<M_KitProductMaster> M_KitProductMaster { get; set; }
        public virtual DbSet<M_KitUnitMaster> M_KitUnitMaster { get; set; }
        public virtual DbSet<M_LeaderWiseOffer> M_LeaderWiseOffer { get; set; }
        public virtual DbSet<M_LedgerMaster> M_LedgerMaster { get; set; }
        public virtual DbSet<M_LogMaster> M_LogMaster { get; set; }
        public virtual DbSet<M_MenuMaster> M_MenuMaster { get; set; }
        public virtual DbSet<M_NewsSeminarMaster> M_NewsSeminarMaster { get; set; }
        public virtual DbSet<M_OccupationMaster> M_OccupationMaster { get; set; }
        public virtual DbSet<M_OfferType> M_OfferType { get; set; }
        public virtual DbSet<M_PackageProductMaster> M_PackageProductMaster { get; set; }
        public virtual DbSet<M_PartyDiscount> M_PartyDiscount { get; set; }
        public virtual DbSet<M_PayModeMaster> M_PayModeMaster { get; set; }
        public virtual DbSet<M_PlanMaster> M_PlanMaster { get; set; }
        public virtual DbSet<M_ProductMaster> M_ProductMaster { get; set; }
        public virtual DbSet<M_QualifyTypeMaster> M_QualifyTypeMaster { get; set; }
        public virtual DbSet<M_SearchTypeMaster> M_SearchTypeMaster { get; set; }
        public virtual DbSet<M_SpecialOfferMaster> M_SpecialOfferMaster { get; set; }
        public virtual DbSet<M_StateDivMaster> M_StateDivMaster { get; set; }
        public virtual DbSet<M_SubCatMaster> M_SubCatMaster { get; set; }
        public virtual DbSet<M_TaxBaseMaster> M_TaxBaseMaster { get; set; }
        public virtual DbSet<M_TaxCatMaster> M_TaxCatMaster { get; set; }
        public virtual DbSet<M_TaxMaster> M_TaxMaster { get; set; }
        public virtual DbSet<M_TaxTypeMaster> M_TaxTypeMaster { get; set; }
        public virtual DbSet<M_ThemeMaster> M_ThemeMaster { get; set; }
        public virtual DbSet<M_UserGroupMaster> M_UserGroupMaster { get; set; }
        public virtual DbSet<M_UserMaster> M_UserMaster { get; set; }
        public virtual DbSet<M_UserPermissionMaster> M_UserPermissionMaster { get; set; }
        public virtual DbSet<MakeKit> MakeKits { get; set; }
        public virtual DbSet<OLDBillDetail> OLDBillDetails { get; set; }
        public virtual DbSet<OLDBillMain> OLDBillMains { get; set; }
        public virtual DbSet<TargetDetail> TargetDetails { get; set; }
        public virtual DbSet<TargetMaster> TargetMasters { get; set; }
        public virtual DbSet<TempBillMain> TempBillMains { get; set; }
        public virtual DbSet<TempCourierMaster> TempCourierMasters { get; set; }
        public virtual DbSet<TempLeaderWiseOffer> TempLeaderWiseOffers { get; set; }
        public virtual DbSet<TempTaxMaster> TempTaxMasters { get; set; }
        public virtual DbSet<TrnBillData> TrnBillDatas { get; set; }
        public virtual DbSet<TrnBillDetail> TrnBillDetails { get; set; }
        public virtual DbSet<TrnBillMain> TrnBillMains { get; set; }
        public virtual DbSet<TrnCancelOrder> TrnCancelOrders { get; set; }
        public virtual DbSet<TrnCancelOrderDetail> TrnCancelOrderDetails { get; set; }
        public virtual DbSet<TrnChallanDetail> TrnChallanDetails { get; set; }
        public virtual DbSet<TrnChallanMain> TrnChallanMains { get; set; }
        public virtual DbSet<trnFoodCart> trnFoodCarts { get; set; }
        public virtual DbSet<trnFoodOrderDetail> trnFoodOrderDetails { get; set; }
        public virtual DbSet<trnFoodOrderMain> trnFoodOrderMains { get; set; }
        public virtual DbSet<TrnFormGeneration> TrnFormGenerations { get; set; }
        public virtual DbSet<TrnLedger> TrnLedgers { get; set; }
        public virtual DbSet<TrnPartyOrderDetail> TrnPartyOrderDetails { get; set; }
        public virtual DbSet<TrnPartyOrderMain> TrnPartyOrderMains { get; set; }
        public virtual DbSet<TrnPaymentConfirmation> TrnPaymentConfirmations { get; set; }
        public virtual DbSet<TrnPaymentHoldDetail> TrnPaymentHoldDetails { get; set; }
        public virtual DbSet<TrnPayModeDetail> TrnPayModeDetails { get; set; }
        public virtual DbSet<TrnProductDispatchDetail> TrnProductDispatchDetails { get; set; }
        public virtual DbSet<TrnProductMain> TrnProductMains { get; set; }
        public virtual DbSet<TrnPurchaseOrderDetail> TrnPurchaseOrderDetails { get; set; }
        public virtual DbSet<TrnPurchaseOrderMain> TrnPurchaseOrderMains { get; set; }
        public virtual DbSet<TrnPurchaseReturnDetail> TrnPurchaseReturnDetails { get; set; }
        public virtual DbSet<TrnPurchaseReturnMain> TrnPurchaseReturnMains { get; set; }
        public virtual DbSet<TrnReceipt> TrnReceipts { get; set; }
        public virtual DbSet<TrnReceiptDetail> TrnReceiptDetails { get; set; }
        public virtual DbSet<TrnSalesReturnDetail> TrnSalesReturnDetails { get; set; }
        public virtual DbSet<TrnSalesReturnMain> TrnSalesReturnMains { get; set; }
        public virtual DbSet<TrnStockAdjustment> TrnStockAdjustments { get; set; }
        public virtual DbSet<TrnStockJv> TrnStockJvs { get; set; }
        public virtual DbSet<TrnUpdateBillDetail> TrnUpdateBillDetails { get; set; }
        public virtual DbSet<VisionOfferProduct> VisionOfferProducts { get; set; }
        public virtual DbSet<VisionOffer> VisionOffers { get; set; }
        public virtual DbSet<WalletReq> WalletReqs { get; set; }
        public virtual DbSet<Web_M_MenuMaster> Web_M_MenuMaster { get; set; }
        public virtual DbSet<Web_M_UserPermissionMaster> Web_M_UserPermissionMaster { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<D_sessnmaster> D_sessnmaster { get; set; }
        public virtual DbSet<DeletedBillDetail> DeletedBillDetails { get; set; }
        public virtual DbSet<DeletedBillMain> DeletedBillMains { get; set; }
        public virtual DbSet<DeletedCurrentStock> DeletedCurrentStocks { get; set; }
        public virtual DbSet<DeletedInwardDetail> DeletedInwardDetails { get; set; }
        public virtual DbSet<DeletedInwardMain> DeletedInwardMains { get; set; }
        public virtual DbSet<DeletedMaxDiscount> DeletedMaxDiscounts { get; set; }
        public virtual DbSet<DeletedReceipt> DeletedReceipts { get; set; }
        public virtual DbSet<DeletedStockJv> DeletedStockJvs { get; set; }
        public virtual DbSet<DeletedVoucher> DeletedVouchers { get; set; }
        public virtual DbSet<Inv_M_MenuMaster> Inv_M_MenuMaster { get; set; }
        public virtual DbSet<Inv_M_ThemeMaster> Inv_M_ThemeMaster { get; set; }
        public virtual DbSet<Inv_TempUserMaster> Inv_TempUserMaster { get; set; }
        public virtual DbSet<Inv_TempUserPermissionMaster> Inv_TempUserPermissionMaster { get; set; }
        public virtual DbSet<KitOffer> KitOffers { get; set; }
        public virtual DbSet<M_BillCondition> M_BillCondition { get; set; }
        public virtual DbSet<M_BloodGroupMaster> M_BloodGroupMaster { get; set; }
        public virtual DbSet<M_ChargesMaster> M_ChargesMaster { get; set; }
        public virtual DbSet<M_ConfigMaster> M_ConfigMaster { get; set; }
        public virtual DbSet<M_FlashMaster> M_FlashMaster { get; set; }
        public virtual DbSet<M_GrpPermissionMaster> M_GrpPermissionMaster { get; set; }
        public virtual DbSet<M_Initials> M_Initials { get; set; }
        public virtual DbSet<M_InvoiceTypeMaster> M_InvoiceTypeMaster { get; set; }
        public virtual DbSet<M_InwardDetail> M_InwardDetail { get; set; }
        public virtual DbSet<M_IsCardIssue> M_IsCardIssue { get; set; }
        public virtual DbSet<M_MaxDiscount> M_MaxDiscount { get; set; }
        public virtual DbSet<M_MemberMaster> M_MemberMaster { get; set; }
        public virtual DbSet<M_MonthSessnMaster> M_MonthSessnMaster { get; set; }
        public virtual DbSet<M_NewCustomer> M_NewCustomer { get; set; }
        public virtual DbSet<M_NewHOVersionInfo> M_NewHOVersionInfo { get; set; }
        public virtual DbSet<M_NewOfferMaster> M_NewOfferMaster { get; set; }
        public virtual DbSet<M_OfferProductType> M_OfferProductType { get; set; }
        public virtual DbSet<M_PartyWiseBillCondition> M_PartyWiseBillCondition { get; set; }
        public virtual DbSet<M_PKGForCustBilling> M_PKGForCustBilling { get; set; }
        public virtual DbSet<M_ProductKitUnitMaster> M_ProductKitUnitMaster { get; set; }
        public virtual DbSet<M_ProfessionMaster> M_ProfessionMaster { get; set; }
        public virtual DbSet<M_ReportType> M_ReportType { get; set; }
        public virtual DbSet<M_Reward> M_Reward { get; set; }
        public virtual DbSet<M_RewardMaster> M_RewardMaster { get; set; }
        public virtual DbSet<M_SearchMethodMaster> M_SearchMethodMaster { get; set; }
        public virtual DbSet<M_SessnMaster> M_SessnMaster { get; set; }
        public virtual DbSet<M_SpecialProductMaster> M_SpecialProductMaster { get; set; }
        public virtual DbSet<M_StockReportType> M_StockReportType { get; set; }
        public virtual DbSet<M_SubCategory> M_SubCategory { get; set; }
        public virtual DbSet<M_UserDataHistory> M_UserDataHistory { get; set; }
        public virtual DbSet<OfferAchvdMem> OfferAchvdMems { get; set; }
        public virtual DbSet<ProdVoucher> ProdVouchers { get; set; }
        public virtual DbSet<RepurchIncome> RepurchIncomes { get; set; }
        public virtual DbSet<TempBankMaster> TempBankMasters { get; set; }
        public virtual DbSet<TempBarCodeMaster> TempBarCodeMasters { get; set; }
        public virtual DbSet<TempBatchMaster> TempBatchMasters { get; set; }
        public virtual DbSet<TempCatMaster> TempCatMasters { get; set; }
        public virtual DbSet<TempChildProductRegistration> TempChildProductRegistrations { get; set; }
        public virtual DbSet<TempCityStateMaster> TempCityStateMasters { get; set; }
        public virtual DbSet<TempCompBankersMaster> TempCompBankersMasters { get; set; }
        public virtual DbSet<TempDispatchMaster> TempDispatchMasters { get; set; }
        public virtual DbSet<TempDistrictMaster> TempDistrictMasters { get; set; }
        public virtual DbSet<TempLedger> TempLedgers { get; set; }
        public virtual DbSet<TempLedgerMaster> TempLedgerMasters { get; set; }
        public virtual DbSet<TempNewHOVersionInfo> TempNewHOVersionInfoes { get; set; }
        public virtual DbSet<TempNewOfferMaster> TempNewOfferMasters { get; set; }
        public virtual DbSet<TempPartyWiseBillCondition> TempPartyWiseBillConditions { get; set; }
        public virtual DbSet<TempProductBookingMaster> TempProductBookingMasters { get; set; }
        public virtual DbSet<TempProductMaster> TempProductMasters { get; set; }
        public virtual DbSet<TempSalesReturnDetail> TempSalesReturnDetails { get; set; }
        public virtual DbSet<TempSalesReturnMain> TempSalesReturnMains { get; set; }
        public virtual DbSet<TempStateDivMaster> TempStateDivMasters { get; set; }
        public virtual DbSet<TempSubCatMaster> TempSubCatMasters { get; set; }
        public virtual DbSet<TempTaxCatMaster> TempTaxCatMasters { get; set; }
        public virtual DbSet<TempVoucher> TempVouchers { get; set; }
        public virtual DbSet<TmpBillDate> TmpBillDates { get; set; }
        public virtual DbSet<TransMaster> TransMasters { get; set; }
        public virtual DbSet<TrnOrderDeliveryDetail> TrnOrderDeliveryDetails { get; set; }
        public virtual DbSet<TrnPartyOrderMainOLD> TrnPartyOrderMainOLDs { get; set; }
        public virtual DbSet<TrnPayModeMaster> TrnPayModeMasters { get; set; }
        public virtual DbSet<TrnPickListDetail> TrnPickListDetails { get; set; }
        public virtual DbSet<TrnPurchaseReqDetail> TrnPurchaseReqDetails { get; set; }
        public virtual DbSet<TrnPurchaseReqMain> TrnPurchaseReqMains { get; set; }
        public virtual DbSet<TrnVoucher> TrnVouchers { get; set; }
    
        public virtual int sp_GetOrderList(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetOrderList", userIDParameter);
        }
    
        public virtual int sp_GetOrderStatus(Nullable<int> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GetOrderStatus", userIDParameter);
        }
    }
}
