//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string UserID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<double> MobileNo { get; set; }
        public string PanNumber { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string F8 { get; set; }
        public string District { get; set; }
        public string EmailId { get; set; }
        public string BankName { get; set; }
        public string AccountName { get; set; }
        public Nullable<double> AccountNo { get; set; }
        public string IFSCCode { get; set; }
        public string SponsorID { get; set; }
        public string SponsorName { get; set; }
        public int SNo { get; set; }
    }
}
