//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnFoodOrderDetail
    {
        public decimal Id { get; set; }
        public decimal OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ProductCode { get; set; }
        public int Quantity { get; set; }
        public int CookID { get; set; }
        public int PckID { get; set; }
        public int DelvID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> TaxPer { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> TotalTax { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public string CookStatus { get; set; }
        public string SuperVisiorStatus { get; set; }
        public string DeliveryStatus { get; set; }
        public string CookRemark { get; set; }
        public string SuperVisorRemark { get; set; }
        public string DeliveryRemark { get; set; }
    }
}
